version = 1

[merge]
automerge_label = "automerge"
blacklist_title_regex = "^WIP.*"
method = "merge"
delete_branch_on_merge = true
notify_on_conflict = true
optimistic_updates = true

[merge.message]
title = "pull_request_title"
include_pr_number = true
body_type = "markdown"
